// Hyprland keybind model for the Keybinds page.
//
// Omarchy Quattro declares every keybind in Lua (`o.bind(keys, description,
// dispatcher, opts)` in `$OMARCHY_PATH/default/hypr/bindings/*.lua` and the
// user's `~/.config/hypr/bindings.lua`). `hyprctl binds` cannot describe
// those binds — every dispatcher is reported as `__lua` with an opaque id and
// `code:N` keys come back empty — so, like Omarchy's own
// `omarchy-menu-keybindings`, the effective list is produced by evaluating the
// user's `hyprland.lua` with a stubbed `hl` table (`scanner.rs`) and replaying
// the recorded `hl.bind` / `hl.unbind` calls in order (`replay.rs`).
//
// User changes never touch `bindings.lua`. They are stored as overrides in
// `~/.config/omarchist/hyprland/keybinds.json` (`overrides.rs`, `store.rs`)
// and rendered into the write-only `~/.config/hypr/omarchist.lua`, which
// Omarchy loads after the user's own files, so it wins.
pub mod chord;
pub mod conflicts;
pub mod keymap;
pub mod replay;
pub mod scanner;
pub mod search;

use std::path::PathBuf;

use serde::{Deserialize, Serialize};

pub use chord::{Chord, ModMask};

/// Which file declared a bind, classified from the Lua source path.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Origin {
    /// `$OMARCHY_PATH/default/...` — shipped with Omarchy.
    Default,
    /// The user's own `~/.config/hypr/*.lua`.
    User,
    /// `~/.config/hypr/omarchist.lua` — generated by this app.
    Omarchist,
}

impl Origin {
    pub fn label(self) -> &'static str {
        match self {
            Origin::Default => "Default",
            Origin::User => "User",
            Origin::Omarchist => "Omarchist",
        }
    }
}

/// What a bind runs. `Exec` is a shell command (`hl.dsp.exec_cmd`), `Lua` is
/// an `hl.dsp.*` expression reconstructed as source text by the scanner
/// (e.g. `hl.dsp.window.close()`), and `Function` is an opaque Lua closure
/// that can only be disabled, never re-emitted.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Dispatcher {
    Exec(String),
    Lua(String),
    Function,
}

impl Dispatcher {
    /// Human-readable command text for the table's Command column.
    pub fn text(&self) -> &str {
        match self {
            Dispatcher::Exec(cmd) | Dispatcher::Lua(cmd) => cmd,
            Dispatcher::Function => "Lua function",
        }
    }

    /// Stable identity string used in `BindIdentity`.
    pub fn identity(&self) -> String {
        match self {
            Dispatcher::Exec(cmd) => format!("exec:{cmd}"),
            Dispatcher::Lua(expr) => format!("lua:{expr}"),
            Dispatcher::Function => "function".to_string(),
        }
    }
}

macro_rules! bind_options {
    ($($field:ident),* $(,)?) => {
        /// Hyprland bind flags (`HL.BindOptions`), minus `description`, which
        /// lives on the bind itself. Every flag defaults to off and is
        /// omitted from JSON when off.
        #[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
        pub struct BindOptions {
            $(
                #[serde(default, skip_serializing_if = "std::ops::Not::not")]
                pub $field: bool,
            )*
        }

        impl BindOptions {
            pub const NAMES: &'static [&'static str] = &[$(stringify!($field)),*];

            /// Parses the scanner's comma-separated flag list. Unknown
            /// names are ignored so newer Hyprland flags don't break scans.
            pub fn from_flags(flags: &str) -> Self {
                let mut options = Self::default();
                for flag in flags.split(',').map(str::trim).filter(|f| !f.is_empty()) {
                    match flag {
                        $(stringify!($field) => options.$field = true,)*
                        _ => {}
                    }
                }
                options
            }

            /// Names of the flags that are set, in declaration order.
            pub fn set_flags(&self) -> Vec<&'static str> {
                let mut set = Vec::new();
                $(if self.$field { set.push(stringify!($field)); })*
                set
            }
        }
    };
}

bind_options!(
    locked,
    repeating,
    release,
    mouse,
    non_consuming,
    transparent,
    ignore_mods,
    long_press,
    submap_universal,
);

/// Stable identity of a scanned bind, used to attach overrides to it across
/// rescans: canonical chord + description + dispatcher text.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct BindIdentity {
    pub keys: String,
    pub description: String,
    pub dispatcher: String,
}

/// Whether a bind is still in effect after replaying every `hl.unbind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BindStatus {
    Active,
    /// Removed by a later `hl.unbind` on the same chord.
    Unbound {
        by_seq: u32,
        by_origin: Origin,
    },
}

/// One `hl.bind` call as observed by the scanner, with its effective status.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Keybind {
    /// Registration order across the whole config (unbinds share the counter).
    pub seq: u32,
    pub chord: Chord,
    /// The keys string exactly as written in Lua, e.g. `"SUPER + code:10"`.
    pub keys_raw: String,
    pub description: String,
    pub dispatcher: Dispatcher,
    pub options: BindOptions,
    pub origin: Origin,
    pub source: PathBuf,
    pub status: BindStatus,
}

impl Keybind {
    pub fn identity(&self) -> BindIdentity {
        BindIdentity {
            keys: self.chord.to_omarchy_string(),
            description: self.description.clone(),
            dispatcher: self.dispatcher.identity(),
        }
    }

    pub fn is_active(&self) -> bool {
        self.status == BindStatus::Active
    }

    /// Function dispatchers cannot be re-emitted under a new chord.
    pub fn is_rebindable(&self) -> bool {
        !matches!(self.dispatcher, Dispatcher::Function)
    }

    /// Description, falling back to the command for undescribed binds
    /// (lid switches and the like).
    pub fn label(&self) -> &str {
        if self.description.is_empty() {
            self.dispatcher.text()
        } else {
            &self.description
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dispatcher_serializes_as_tagged_values() {
        let exec = serde_json::to_string(&Dispatcher::Exec("ls".into())).unwrap();
        let lua = serde_json::to_string(&Dispatcher::Lua("hl.dsp.window.close()".into())).unwrap();
        let func = serde_json::to_string(&Dispatcher::Function).unwrap();
        assert_eq!(exec, r#"{"exec":"ls"}"#);
        assert_eq!(lua, r#"{"lua":"hl.dsp.window.close()"}"#);
        assert_eq!(func, r#""function""#);
        assert_eq!(
            serde_json::from_str::<Dispatcher>(&exec).unwrap(),
            Dispatcher::Exec("ls".into())
        );
        assert_eq!(
            serde_json::from_str::<Dispatcher>(&func).unwrap(),
            Dispatcher::Function
        );
    }

    #[test]
    fn bind_options_round_trip_flags_and_skip_false_in_json() {
        let options = BindOptions::from_flags("locked, repeating,unknown_flag");
        assert!(options.locked);
        assert!(options.repeating);
        assert!(!options.release);
        assert_eq!(options.set_flags(), vec!["locked", "repeating"]);
        assert_eq!(
            serde_json::to_string(&options).unwrap(),
            r#"{"locked":true,"repeating":true}"#
        );
        assert_eq!(
            serde_json::to_string(&BindOptions::default()).unwrap(),
            "{}"
        );
        assert_eq!(
            serde_json::from_str::<BindOptions>("{}").unwrap(),
            BindOptions::default()
        );
    }

    #[test]
    fn keybind_identity_uses_canonical_chord_and_dispatcher() {
        let bind = Keybind {
            seq: 1,
            chord: Chord::parse("shift + super + k").unwrap(),
            keys_raw: "shift + super + k".into(),
            description: "Keybindings".into(),
            dispatcher: Dispatcher::Exec("omarchy-menu-keybindings".into()),
            options: BindOptions::default(),
            origin: Origin::Default,
            source: PathBuf::from("/x.lua"),
            status: BindStatus::Active,
        };
        let id = bind.identity();
        assert_eq!(id.keys, "SUPER + SHIFT + K");
        assert_eq!(id.dispatcher, "exec:omarchy-menu-keybindings");
        assert!(bind.is_rebindable());
        assert_eq!(bind.label(), "Keybindings");
    }
}
