//! Override files generated from the theme's palette with some colors
//! changed. A bundle renders Omarchy's own templates for its files from the
//! theme's `colors.toml` with the user's changes applied, so one set of colors
//! drives several files (every terminal config at once) and the colors left
//! alone keep following the palette. The changes live in `omarchist.json`
//! (`EditingTheme::palettes`); the files are only ever generated.

use std::collections::BTreeMap;
use std::fs;
use std::sync::atomic::{AtomicU64, Ordering};

use crate::error::{Error, Result};
use crate::shell::theme_sh_commands::theme_color_all;
use crate::system::themes::theme_management::colors::render_colors_toml;
use crate::system::themes::theme_management::update_theme;
use crate::types::themes::ColorsConfig;

use super::files::{self, read_template};
use super::registry::{Category, OverrideSpec, Seed, find};
use super::template::{Palette, render};

/// Files generated together from one set of colors.
#[derive(Debug)]
pub struct PaletteBundle {
    /// Key in `EditingTheme::palettes`.
    pub id: &'static str,
    pub app: &'static str,
    pub description: &'static str,
    pub category: Category,
    pub files: &'static [&'static str],
    /// Programs that consume the files. Empty when always relevant.
    pub binaries: &'static [&'static str],
}

pub const BUNDLES: &[PaletteBundle] = &[
    PaletteBundle {
        id: "terminals",
        app: "Terminal Colors",
        description: "One set of colors for Alacritty, Kitty, Ghostty, and Foot.",
        category: Category::Terminals,
        files: &["alacritty.toml", "kitty.conf", "ghostty.conf", "foot.ini"],
        binaries: &["alacritty", "kitty", "ghostty", "foot"],
    },
    PaletteBundle {
        id: "terminal-menus",
        app: "Terminal Menus",
        description: "Omarchy's menus and prompts in the terminal.",
        category: Category::Desktop,
        files: &["gum_env.lua"],
        binaries: &[],
    },
    PaletteBundle {
        id: "screen-share-picker",
        app: "Screen Share Picker",
        description: "The window and screen picker shown when an app starts sharing.",
        category: Category::Desktop,
        files: &["hyprland-preview-share-picker.css"],
        binaries: &["hyprland-preview-share-picker"],
    },
    PaletteBundle {
        id: "obsidian",
        app: "Obsidian",
        description: "The Omarchy theme copied into every Obsidian vault.",
        category: Category::Editors,
        files: &["obsidian.css"],
        binaries: &["obsidian"],
    },
];

pub fn find_bundle(id: &str) -> Option<&'static PaletteBundle> {
    BUNDLES.iter().find(|bundle| bundle.id == id)
}

/// The bundle a file is generated by, if any.
pub fn bundle_of(file: &str) -> Option<&'static PaletteBundle> {
    BUNDLES.iter().find(|bundle| bundle.files.contains(&file))
}

/// A `colors.toml` key a bundle can change, labelled as on the Colors tab.
#[derive(Debug)]
pub struct BaseKey {
    pub key: &'static str,
    pub label: &'static str,
    pub group: &'static str,
}

const fn base(key: &'static str, label: &'static str, group: &'static str) -> BaseKey {
    BaseKey { key, label, group }
}

pub const BASE_KEYS: &[BaseKey] = &[
    base("accent", "Accent", "Primary Colors"),
    base("background", "Background", "Primary Colors"),
    base("foreground", "Foreground", "Primary Colors"),
    base("selection_background", "Background", "Selection Colors"),
    base("selection_foreground", "Foreground", "Selection Colors"),
    base("color0", "Black", "Normal Colors"),
    base("color1", "Red", "Normal Colors"),
    base("color2", "Green", "Normal Colors"),
    base("color3", "Yellow", "Normal Colors"),
    base("color4", "Blue", "Normal Colors"),
    base("color5", "Magenta", "Normal Colors"),
    base("color6", "Cyan", "Normal Colors"),
    base("color7", "White", "Normal Colors"),
    base("color8", "Black", "Bright Colors"),
    base("color9", "Red", "Bright Colors"),
    base("color10", "Green", "Bright Colors"),
    base("color11", "Yellow", "Bright Colors"),
    base("color12", "Blue", "Bright Colors"),
    base("color13", "Magenta", "Bright Colors"),
    base("color14", "Cyan", "Bright Colors"),
    base("color15", "White", "Bright Colors"),
];

/// The value of a base key in a palette.
pub fn base_value(colors: &ColorsConfig, key: &str) -> Option<String> {
    serde_json::to_value(colors)
        .ok()?
        .get(key)?
        .as_str()
        .map(str::to_string)
}

/// `colors` with `overrides` applied; unknown keys are ignored.
pub fn with_overrides(colors: &ColorsConfig, overrides: &BTreeMap<String, String>) -> ColorsConfig {
    let Ok(serde_json::Value::Object(mut map)) = serde_json::to_value(colors) else {
        return colors.clone();
    };
    for (key, value) in overrides {
        if BASE_KEYS.iter().any(|base| base.key == key) {
            map.insert(key.clone(), serde_json::Value::String(value.clone()));
        }
    }
    serde_json::from_value(serde_json::Value::Object(map)).unwrap_or_else(|_| colors.clone())
}

/// Resolves a palette the way Omarchy does, derived shades included.
pub fn resolve(colors: &ColorsConfig) -> Result<Palette> {
    static COUNTER: AtomicU64 = AtomicU64::new(0);
    let path = std::env::temp_dir().join(format!(
        "omarchist-colors-{}-{}.toml",
        std::process::id(),
        COUNTER.fetch_add(1, Ordering::Relaxed)
    ));
    fs::write(&path, render_colors_toml(colors))
        .map_err(|e| Error::io("Failed to write a temporary colors.toml", e))?;
    let output = theme_color_all(&path);
    let _ = fs::remove_file(&path);
    Ok(Palette::parse(&output?))
}

fn specs(bundle: &PaletteBundle) -> Result<Vec<&'static OverrideSpec>> {
    bundle
        .files
        .iter()
        .map(|file| {
            find(file).ok_or_else(|| Error::Invalid(format!("{file} is not an override file")))
        })
        .collect()
}

type Rendered = Vec<(&'static OverrideSpec, String)>;

fn render_bundle(bundle: &PaletteBundle, palette: &Palette) -> Result<Rendered> {
    specs(bundle)?
        .into_iter()
        .map(|spec| match spec.seed {
            Seed::Template(template) => Ok((spec, render(&read_template(template)?, palette))),
            _ => Err(Error::Invalid(format!("{} has no template", spec.file))),
        })
        .collect()
}

/// The base keys whose value shows up in the bundle's files, found by
/// changing each one and seeing whether the rendered files change.
pub fn relevant_keys(
    bundle: &PaletteBundle,
    colors: &ColorsConfig,
) -> Result<Vec<&'static BaseKey>> {
    let text = |rendered: Rendered| -> Vec<String> {
        rendered.into_iter().map(|(_, content)| content).collect()
    };
    let baseline = text(render_bundle(bundle, &resolve(colors)?)?);
    let mut relevant = Vec::new();
    for base in BASE_KEYS {
        let current = base_value(colors, base.key).unwrap_or_default();
        let probe = if current.eq_ignore_ascii_case("#0f1e2d") {
            "#d2e1f0"
        } else {
            "#0f1e2d"
        };
        let probed = with_overrides(
            colors,
            &BTreeMap::from([(base.key.to_string(), probe.to_string())]),
        );
        if text(render_bundle(bundle, &resolve(&probed)?)?) != baseline {
            relevant.push(base);
        }
    }
    Ok(relevant)
}

/// Writes the bundle's files from the theme's colors with `overrides` applied.
pub fn generate(
    theme: &str,
    bundle: &PaletteBundle,
    colors: &ColorsConfig,
    overrides: &BTreeMap<String, String>,
) -> Result<()> {
    let palette = resolve(&with_overrides(colors, overrides))?;
    for (spec, content) in render_bundle(bundle, &palette)? {
        files::write(theme, spec, &content)?;
    }
    Ok(())
}

/// Deletes the bundle's files so Omarchy generates them again.
pub fn remove_files(theme: &str, bundle: &PaletteBundle) -> Result<()> {
    for spec in specs(bundle)? {
        files::remove(theme, spec)?;
    }
    Ok(())
}

/// The bundle's files the theme ships, whether or not Omarchist generated
/// them; a theme from an older Omarchist can carry hand-written ones.
pub fn existing_files(theme: &str, bundle: &PaletteBundle) -> Vec<&'static str> {
    specs(bundle)
        .unwrap_or_default()
        .into_iter()
        .filter(|spec| files::status(theme, spec) == files::OverrideStatus::Custom)
        .map(|spec| spec.file)
        .collect()
}

/// Turns the bundle on with `overrides`, or off with `None`, and rewrites or
/// removes its files. Saving the theme regenerates every bundle that is on.
pub fn set(
    theme: &str,
    bundle: &PaletteBundle,
    overrides: Option<BTreeMap<String, String>>,
) -> Result<()> {
    let enabled = overrides.is_some();
    update_theme(theme, |data| match overrides {
        Some(overrides) => {
            data.palettes.insert(bundle.id.to_string(), overrides);
        }
        None => {
            data.palettes.remove(bundle.id);
        }
    })?;
    if !enabled {
        remove_files(theme, bundle)?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::collections::{BTreeMap, HashSet};

    use super::{BASE_KEYS, BUNDLES, base_value, bundle_of, with_overrides};
    use crate::system::themes::overrides::registry::{EditorKind, OVERRIDES, Seed, find};
    use crate::types::themes::ColorsConfig;

    #[test]
    fn bundle_files_are_templated_palette_overrides() {
        let mut seen = HashSet::new();
        for bundle in BUNDLES {
            for file in bundle.files {
                assert!(seen.insert(*file), "{file} is in two bundles");
                let spec = find(file).unwrap_or_else(|| panic!("{file} is not registered"));
                assert!(matches!(spec.seed, Seed::Template(_)), "{file}");
                assert_eq!(spec.editor, EditorKind::Palette, "{file}");
                assert_eq!(spec.category, bundle.category, "{file}");
            }
        }
        for spec in OVERRIDES {
            if spec.editor == EditorKind::Palette {
                assert!(
                    bundle_of(spec.file).is_some(),
                    "{} has no bundle",
                    spec.file
                );
            }
        }
    }

    #[test]
    fn overrides_replace_only_base_keys() {
        let colors = ColorsConfig::default();
        let changed = with_overrides(
            &colors,
            &BTreeMap::from([
                ("color1".to_string(), "#123456".to_string()),
                ("mode".to_string(), "light".to_string()),
            ]),
        );
        assert_eq!(changed.color1, "#123456");
        assert_eq!(changed.mode, colors.mode);
        assert_eq!(changed.color2, colors.color2);
        for base in BASE_KEYS {
            assert!(base_value(&colors, base.key).is_some(), "{}", base.key);
        }
    }

    #[test]
    fn terminal_colors_find_the_ansi_palette() {
        if std::process::Command::new("omarchy-theme-color")
            .arg("--help")
            .output()
            .is_err()
        {
            return;
        }
        let bundle = super::find_bundle("terminals").unwrap();
        let keys: Vec<&str> = super::relevant_keys(bundle, &ColorsConfig::default())
            .unwrap()
            .into_iter()
            .map(|base| base.key)
            .collect();
        for key in ["background", "foreground", "color1", "color9", "color15"] {
            assert!(keys.contains(&key), "{key} missing from {keys:?}");
        }
    }
}
