# This is an Omarchist flow: https://omarchist.com/flows/

format = 2
name = "Search selection"
description = "Searches the web for the text you have selected."
icon = "globe"
on_error = "stop"

[meta]
author = "Omarchist"

[[step]]
type = "action"
action = "web.search"
query = "{{selection}}"
