# This is an Omarchist flow: https://omarchist.com/flows/

format = 2
name = "Search selection"
description = "Searches the web for the text you have selected, or for the text you start it with."
icon = "globe"
on_error = "stop"
input = "selection"

[meta]
author = "Omarchist"

[[step]]
type = "action"
action = "web.search"
query = "{{input}}"
