// Generates `~/.config/hypr/omarchist.lua`, a write-only file Omarchist owns
// entirely — it is never read back (the round-trip source of truth is
// `~/.config/omarchist/hyprland/state.json`, see `manager.rs`). Confirmed
// against the real omacom/omarchy@quattro source (`config/hypr/looknfeel.lua`,
// `config/hypr/input.lua`): Hyprland settings are applied via one global
// merge function, `hl.config({ <section> = { <key> = <value>, ... } })`,
// where section/subsection names match hyprlang's own config sections
// 1:1 (general, decoration.blur, input.touchpad, etc).
//
// Rather than re-encoding every field's default value a second time (as the
// old hyprlang `writer.rs` did, in ~150 hand-written `if field != N` checks),
// this diffs the actual config against `HyprlandConfig::default()` via JSON
// and only emits keys that actually changed. `HyprlandConfig::default()`
// stays the single source of truth for defaults.
use serde_json::Value;

use crate::types::hyprland_config::HyprlandConfig;

// Hyprland option names that don't match their Rust field name — hyprlang
// itself is inconsistent here (confirmed against writer.rs / Hyprland docs:
// touchpad's tap-to-click/tap-and-drag are hyphenated, unlike every other
// option, which is why Rust uses underscored idents for them).
fn hypr_key_name(rust_field: &str) -> &str {
    match rust_field {
        "tap_to_click" => "tap-to-click",
        "tap_and_drag" => "tap-and-drag",
        other => other,
    }
}

pub fn write_lua_config(config: &HyprlandConfig) -> String {
    let mut output = String::new();
    output.push_str(
        "-- Generated by Omarchist — do not edit manually\n\
         -- Loaded via require(\"hypr.omarchist\") from your hyprland.lua\n\n",
    );

    let default = HyprlandConfig::default();
    let actual_json = serde_json::to_value(config).unwrap_or(Value::Null);
    let default_json = serde_json::to_value(&default).unwrap_or(Value::Null);

    let (Value::Object(actual_sections), Value::Object(default_sections)) =
        (&actual_json, &default_json)
    else {
        return output;
    };

    for (section, actual_section) in actual_sections {
        let default_section = default_sections.get(section).unwrap_or(&Value::Null);
        if let Some(diff) = diff_value(actual_section, default_section) {
            output.push_str(&format!(
                "hl.config({{ {} = {} }})\n",
                section,
                lua_literal(&diff)
            ));
        }
    }

    output
}

// Recursively diffs two JSON values, keeping only object keys whose values
// differ (diffing nested objects — subsections like `snap`/`blur`/`touchpad`
// — recursively too). Returns `None` when nothing differs.
fn diff_value(actual: &Value, default: &Value) -> Option<Value> {
    match (actual, default) {
        (Value::Object(a), Value::Object(d)) => {
            let mut out = serde_json::Map::new();
            for (key, actual_val) in a {
                let default_val = d.get(key).unwrap_or(&Value::Null);
                if actual_val.is_object() {
                    if let Some(nested) = diff_value(actual_val, default_val) {
                        out.insert(key.clone(), nested);
                    }
                } else if actual_val != default_val {
                    out.insert(key.clone(), actual_val.clone());
                }
            }
            if out.is_empty() {
                None
            } else {
                Some(Value::Object(out))
            }
        }
        _ if actual != default => Some(actual.clone()),
        _ => None,
    }
}

// Renders a JSON value as a Lua literal. Object keys use bracketed string
// syntax (`["key"] = value`) so hyphenated Hyprland option names round-trip
// correctly without special-casing the table syntax itself.
fn lua_literal(value: &Value) -> String {
    match value {
        Value::Object(map) => {
            let entries: Vec<String> = map
                .iter()
                .map(|(k, v)| format!("[\"{}\"] = {}", hypr_key_name(k), lua_literal(v)))
                .collect();
            format!("{{ {} }}", entries.join(", "))
        }
        Value::Array(items) => {
            let entries: Vec<String> = items.iter().map(lua_literal).collect();
            format!("{{ {} }}", entries.join(", "))
        }
        Value::String(s) => lua_string(s),
        Value::Number(n) => n.to_string(),
        Value::Bool(b) => b.to_string(),
        Value::Null => "nil".to_string(),
    }
}

fn lua_string(s: &str) -> String {
    let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{}\"", escaped)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn write_lua_config_default_config_emits_nothing() {
        let config = HyprlandConfig::default();
        let output = write_lua_config(&config);

        assert!(
            !output.contains("hl.config"),
            "a config identical to the default should emit no hl.config calls, got: {output}"
        );
    }

    #[test]
    fn write_lua_config_changed_field_is_emitted() {
        let mut config = HyprlandConfig::default();
        config.general.border_size = 4;

        let output = write_lua_config(&config);

        assert!(output.contains("hl.config({ general = "));
        assert!(output.contains("[\"border_size\"] = 4"));
        assert!(
            !output.contains("gaps_in"),
            "unchanged fields should not be emitted, got: {output}"
        );
    }

    #[test]
    fn write_lua_config_nested_subsection_diff_only_includes_changed_key() {
        let mut config = HyprlandConfig::default();
        config.decoration.blur.size = 4;

        let output = write_lua_config(&config);

        assert!(output.contains("[\"blur\"]"));
        assert!(output.contains("[\"size\"] = 4"));
        assert!(!output.contains("passes"));
    }

    #[test]
    fn write_lua_config_hyphenated_touchpad_keys_are_translated() {
        let mut config = HyprlandConfig::default();
        config.input.touchpad.tap_to_click = false;
        config.input.touchpad.tap_and_drag = false;

        let output = write_lua_config(&config);

        assert!(output.contains("[\"tap-to-click\"] = false"));
        assert!(output.contains("[\"tap-and-drag\"] = false"));
        assert!(!output.contains("tap_to_click"));
        assert!(!output.contains("tap_and_drag"));
    }

    #[test]
    fn write_lua_config_string_values_are_quoted_and_escaped() {
        let mut config = HyprlandConfig::default();
        config.general.layout = "master \"quoted\"".to_string();

        let output = write_lua_config(&config);

        // The layout string itself should be quoted with internal quotes escaped.
        assert!(output.contains("master \\\"quoted\\\""));
    }

    #[test]
    fn diff_value_identical_objects_returns_none() {
        let a = serde_json::json!({ "x": 1, "y": "hi" });
        let b = a.clone();
        assert!(diff_value(&a, &b).is_none());
    }

    #[test]
    fn diff_value_returns_only_changed_keys() {
        let a = serde_json::json!({ "x": 1, "y": 2 });
        let b = serde_json::json!({ "x": 1, "y": 3 });
        let diff = diff_value(&a, &b).expect("expected a diff");
        assert_eq!(diff, serde_json::json!({ "y": 2 }));
    }

    #[test]
    fn lua_literal_renders_bool_number_and_string() {
        assert_eq!(lua_literal(&serde_json::json!(true)), "true");
        assert_eq!(lua_literal(&serde_json::json!(42)), "42");
        assert_eq!(lua_literal(&serde_json::json!("hi")), "\"hi\"");
    }
}
