// Generates `~/.config/hypr/omarchist.lua`, a write-only file Omarchist owns
// entirely; it is never read back (the round-trip source of truth is
// `~/.config/omarchist/hyprland/state.json`, see `manager.rs`). Settings are
// applied the way Omarchy's own `config/hypr/looknfeel.lua` and `input.lua`
// do it, through `hl.config({ <section> = { <key> = <value>, ... } })`, with
// the key names of Hyprland's Lua API (`input.touchpad.tap_to_click`, not
// hyprlang's `tap-to-click`).
//
// The input is the sparse overrides object (only the keys the user changed),
// rendered as is: nothing is diffed against defaults, so Omarchy's own
// values can never end up pinned in the file.
use serde_json::Value;

pub fn write_lua_config(overrides: &Value) -> String {
    let mut output = String::new();
    output.push_str(
        "-- Generated by Omarchist — do not edit manually\n\
         -- Loaded via require(\"hypr.omarchist\") from your hyprland.lua\n\n",
    );

    let Value::Object(sections) = overrides else {
        return output;
    };
    for (section, values) in sections {
        if values.as_object().is_some_and(|map| !map.is_empty()) {
            output.push_str(&format!(
                "hl.config({{ {} = {} }})\n",
                section,
                lua_literal(values)
            ));
        }
    }

    output
}

// Renders a JSON value as a Lua literal. Object keys use bracketed string
// syntax (`["key"] = value`) so any option name round-trips without
// special-casing the table syntax itself.
fn lua_literal(value: &Value) -> String {
    match value {
        Value::Object(map) => {
            let entries: Vec<String> = map
                .iter()
                .map(|(k, v)| format!("[{}] = {}", lua_string(k), lua_literal(v)))
                .collect();
            format!("{{ {} }}", entries.join(", "))
        }
        Value::Array(items) => {
            let entries: Vec<String> = items.iter().map(lua_literal).collect();
            format!("{{ {} }}", entries.join(", "))
        }
        Value::String(s) => lua_string(s),
        Value::Number(n) => n.to_string(),
        Value::Bool(b) => b.to_string(),
        Value::Null => "nil".to_string(),
    }
}

/// Renders `omarchist.lua` in full: the settings, the keybind overrides
/// block (see `keybinds::overrides::emit_keybinds_lua`), and the submap the
/// keystroke recorder relies on (see `keybinds::submap`).
pub fn render_omarchist_lua(overrides: &Value, keybinds_lua: &str) -> String {
    let mut output = write_lua_config(overrides);
    if !keybinds_lua.is_empty() {
        output.push_str("\n-- Keybinds (managed on the Keybinds page)\n");
        output.push_str(keybinds_lua);
    }
    output.push_str(
        "\n-- Submap the Keybinds page switches to while recording a keystroke,\n\
         -- so Hyprland lets every chord through to Omarchist.\n",
    );
    output.push_str(&crate::system::keybinds::submap::define_recording_submap_lua());
    output
}

/// A double-quoted Lua string literal. Newlines are escaped too so a
/// value can never break out of the single-line calls this file emits.
pub(crate) fn lua_string(s: &str) -> String {
    let escaped = s
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r");
    format!("\"{}\"", escaped)
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    #[test]
    fn no_overrides_emit_no_config_calls() {
        let output = write_lua_config(&json!({}));
        assert!(!output.contains("hl.config"), "got: {output}");
        let output = write_lua_config(&json!({ "general": {} }));
        assert!(
            !output.contains("hl.config"),
            "empty sections are skipped: {output}"
        );
    }

    #[test]
    fn only_the_overridden_keys_are_emitted() {
        let output = write_lua_config(&json!({ "general": { "border_size": 4 } }));
        assert!(output.contains("hl.config({ general = { [\"border_size\"] = 4 } })"));
        assert!(!output.contains("gaps_in"));
    }

    #[test]
    fn nested_subsections_render_as_nested_tables() {
        let output = write_lua_config(
            &json!({ "decoration": { "blur": { "size": 4 } }, "input": { "touchpad": { "tap_to_click": false } } }),
        );
        assert!(output.contains("[\"blur\"] = { [\"size\"] = 4 }"));
        // The Lua API spells these with underscores, unlike hyprlang.
        assert!(output.contains("[\"tap_to_click\"] = false"));
        assert!(!output.contains("tap-to-click"));
    }

    #[test]
    fn arrays_render_as_sequences_for_vec2_values() {
        let output =
            write_lua_config(&json!({ "decoration": { "shadow": { "offset": [2, -3.5] } } }));
        assert!(
            output.contains("[\"offset\"] = { 2, -3.5 }"),
            "got: {output}"
        );
    }

    #[test]
    fn string_values_are_quoted_and_escaped() {
        let output = write_lua_config(&json!({ "general": { "layout": "master \"quoted\"" } }));
        assert!(output.contains("master \\\"quoted\\\""));
    }

    #[test]
    fn render_omarchist_lua_appends_keybinds_after_settings() {
        let overrides = json!({ "general": { "border_size": 4 } });

        let plain = render_omarchist_lua(&overrides, "");
        assert!(plain.starts_with(&write_lua_config(&overrides)));
        assert!(plain.contains("hl.define_submap(\"omarchist-recording\""));
        assert!(!plain.contains("-- Keybinds (managed"));

        let with_keybinds = render_omarchist_lua(&overrides, "hl.unbind(\"SUPER + K\")\n");
        let settings_at = with_keybinds.find("hl.config").unwrap();
        let keybinds_at = with_keybinds.find("hl.unbind").unwrap();
        assert!(settings_at < keybinds_at);
        assert!(with_keybinds.contains("-- Keybinds (managed on the Keybinds page)"));
    }

    #[test]
    fn lua_string_escapes_quotes_backslashes_and_newlines() {
        assert_eq!(lua_string("a\"b\\c\nd"), "\"a\\\"b\\\\c\\nd\"");
    }

    #[test]
    fn lua_literal_renders_bool_number_and_string() {
        assert_eq!(lua_literal(&json!(true)), "true");
        assert_eq!(lua_literal(&json!(42)), "42");
        assert_eq!(lua_literal(&json!("hi")), "\"hi\"");
    }
}
