use dirs::home_dir;
use json_comments::StripComments;
use serde::{Deserialize, Serialize};
use serde_json::{json, Map, Value};
use std::collections::{BTreeMap, HashSet};
use std::fs;
use std::io::Write;
use std::path::PathBuf;

const KNOWN_MODULE_KEYS: &[&str] = &[
    "custom/omarchy",
    "hyprland/workspaces",
    "hyprland/window",
    "clock",
    "custom/update",
    "custom/screenrecording-indicator",
    "group/tray-expander",
    "custom/expand-icon",
    "tray",
    "bluetooth",
    "network",
    "pulseaudio",
    "cpu",
    "battery",
];

const CONFIG_HEADER: &str = "// Generated by Omarchist Waybar editor\n// Manual edits for unsupported fields will be preserved.\n";

#[derive(Debug, thiserror::Error)]
pub enum WaybarConfigError {
    #[error("Unable to resolve home directory")]
    HomeDirNotFound,
    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),
    #[error("Failed to parse Waybar config: {0}")]
    Parse(String),
    #[error("Serialization error: {0}")]
    Serialization(#[from] serde_json::Error),
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct WaybarLayout {
    pub left: Vec<String>,
    pub center: Vec<String>,
    pub right: Vec<String>,
    pub hidden: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WaybarGlobals {
    pub layer: String,
    pub position: String,
    pub height: f64,
    pub spacing: f64,
    pub background: String,
    pub foreground: String,
}

impl Default for WaybarGlobals {
    fn default() -> Self {
        Self {
            layer: "top".to_string(),
            position: "top".to_string(),
            height: 26.0,
            spacing: 0.0,
            background: "#1e1e1e".to_string(),
            foreground: "#d4d4d8".to_string(),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WaybarConfigSnapshot {
    pub layout: WaybarLayout,
    pub globals: WaybarGlobals,
    pub modules: BTreeMap<String, Value>,
    pub passthrough: Value,
    pub raw_json: String,
}

impl Default for WaybarConfigSnapshot {
    fn default() -> Self {
        Self {
            layout: WaybarLayout::default(),
            globals: WaybarGlobals::default(),
            modules: default_modules_map(),
            passthrough: json!({
                "reload_style_on_change": true
            }),
            raw_json: String::new(),
        }
    }
}

#[derive(Debug, Clone, Deserialize)]
pub struct SaveWaybarConfigPayload {
    pub layout: WaybarLayout,
    pub globals: WaybarGlobals,
    pub modules: BTreeMap<String, Value>,
    pub passthrough: Value,
}

pub struct WaybarConfigService {
    config_path: PathBuf,
}

impl WaybarConfigService {
    pub fn new() -> Result<Self, WaybarConfigError> {
        let mut path = home_dir().ok_or(WaybarConfigError::HomeDirNotFound)?;
        path.push(".config/waybar/config.jsonc");
        Ok(Self { config_path: path })
    }

    pub fn load_snapshot(&self) -> Result<WaybarConfigSnapshot, WaybarConfigError> {
        self.ensure_parent_exists()?;

        if !self.config_path.exists() {
            let value = default_root_value();
            self.write_value(&value)?;
            let raw_json = serde_json::to_string_pretty(&value)?;
            return Ok(self.build_snapshot(value, raw_json));
        }

        let (value, raw_json) = self.read_value()?;
        Ok(self.build_snapshot(value, raw_json))
    }

    pub fn save_snapshot(
        &self,
        payload: &SaveWaybarConfigPayload,
    ) -> Result<WaybarConfigSnapshot, WaybarConfigError> {
        self.ensure_parent_exists()?;
        let global_defaults = WaybarGlobals::default();

        let mut seen = HashSet::new();
        let left = unique_ordered(payload.layout.left.clone(), &mut seen);
        let center = unique_ordered(payload.layout.center.clone(), &mut seen);
        let right = unique_ordered(payload.layout.right.clone(), &mut seen);

        let mut root_map = match payload.passthrough.clone() {
            Value::Object(map) => map,
            _ => Map::new(),
        };

        root_map.insert(
            "layer".to_string(),
            Value::String(payload.globals.layer.clone()),
        );
        root_map.insert(
            "position".to_string(),
            Value::String(payload.globals.position.clone()),
        );
        root_map.insert(
            "spacing".to_string(),
            Value::Number(number_from_f64(
                payload.globals.spacing,
                global_defaults.spacing,
            )),
        );
        root_map.insert(
            "modules-left".to_string(),
            Value::Array(left.iter().map(|id| Value::String(id.clone())).collect()),
        );
        root_map.insert(
            "modules-center".to_string(),
            Value::Array(center.iter().map(|id| Value::String(id.clone())).collect()),
        );
        root_map.insert(
            "modules-right".to_string(),
            Value::Array(right.iter().map(|id| Value::String(id.clone())).collect()),
        );

        root_map.insert(
            "height".to_string(),
            Value::Number(number_from_f64(
                payload.globals.height,
                global_defaults.height,
            )),
        );

        for key in KNOWN_MODULE_KEYS {
            root_map.remove(*key);
        }

        let defaults = default_modules_map();
        for key in KNOWN_MODULE_KEYS {
            let value = payload.modules.get(*key).cloned().unwrap_or_else(|| {
                defaults
                    .get(*key)
                    .cloned()
                    .unwrap_or(Value::Object(Map::new()))
            });
            root_map.insert((*key).to_string(), value);
        }

        let mut omarchist = match root_map.remove("_omarchist") {
            Some(Value::Object(map)) => map,
            _ => Map::new(),
        };
        let mut globals_map = Map::new();

        if payload.globals.background != global_defaults.background {
            globals_map.insert(
                "background".to_string(),
                Value::String(payload.globals.background.clone()),
            );
        }
        if payload.globals.foreground != global_defaults.foreground {
            globals_map.insert(
                "foreground".to_string(),
                Value::String(payload.globals.foreground.clone()),
            );
        }

        if !globals_map.is_empty() {
            omarchist.insert("globals".to_string(), Value::Object(globals_map));
        }
        if !omarchist.is_empty() {
            root_map.insert("_omarchist".to_string(), Value::Object(omarchist));
        }

        let config_value = Value::Object(root_map);
        self.write_value(&config_value)?;
        let raw_json = serde_json::to_string_pretty(&config_value)?;
        Ok(self.build_snapshot(config_value, raw_json))
    }

    fn ensure_parent_exists(&self) -> Result<(), WaybarConfigError> {
        if let Some(parent) = self.config_path.parent() {
            if !parent.exists() {
                fs::create_dir_all(parent)?;
            }
            return Ok(());
        }
        Ok(())
    }

    fn write_value(&self, value: &Value) -> Result<(), WaybarConfigError> {
        let prettified = serde_json::to_string_pretty(value)?;
        let mut buffer = String::new();
        buffer.push_str(CONFIG_HEADER);
        buffer.push('\n');
        buffer.push_str(&prettified);
        buffer.push('\n');

        let mut file = fs::File::create(&self.config_path)?;
        file.write_all(buffer.as_bytes())?;
        file.flush()?;
        Ok(())
    }

    fn read_value(&self) -> Result<(Value, String), WaybarConfigError> {
        let contents = fs::read_to_string(&self.config_path)?;
        let mut reader = StripComments::new(contents.as_bytes());
        let value: Value = serde_json::from_reader(&mut reader)
            .map_err(|err| WaybarConfigError::Parse(err.to_string()))?;
        let raw_json = serde_json::to_string_pretty(&value)?;
        Ok((value, raw_json))
    }

    fn build_snapshot(&self, value: Value, raw_json: String) -> WaybarConfigSnapshot {
        let mut root_map = match value {
            Value::Object(map) => map,
            _ => Map::new(),
        };

        let layout = WaybarLayout {
            left: take_string_array(root_map.remove("modules-left"), default_left_modules()),
            center: take_string_array(root_map.remove("modules-center"), default_center_modules()),
            right: take_string_array(root_map.remove("modules-right"), default_right_modules()),
            hidden: vec![],
        };

        let mut globals = WaybarGlobals::default();
        if let Some(layer) = root_map
            .remove("layer")
            .and_then(|v| v.as_str().map(|s| s.to_string()))
        {
            globals.layer = layer;
        }
        if let Some(position) = root_map
            .remove("position")
            .and_then(|v| v.as_str().map(|s| s.to_string()))
        {
            globals.position = position;
        }

        if let Some(height) = root_map.remove("height").and_then(|v| v.as_f64()) {
            globals.height = height;
        }

        if let Some(spacing) = root_map.remove("spacing").and_then(|v| v.as_f64()) {
            globals.spacing = spacing;
        }

        if let Some(Value::Object(omarchist)) = root_map.get_mut("_omarchist") {
            if let Some(Value::Object(globals_obj)) = omarchist.remove("globals") {
                if let Some(height) = globals_obj.get("height").and_then(|v| v.as_f64()) {
                    globals.height = height;
                }
                if let Some(background) = globals_obj.get("background").and_then(|v| v.as_str()) {
                    globals.background = background.to_string();
                }
                if let Some(foreground) = globals_obj.get("foreground").and_then(|v| v.as_str()) {
                    globals.foreground = foreground.to_string();
                }
            }
            if omarchist.is_empty() {
                root_map.remove("_omarchist");
            }
        }

        let mut modules = default_modules_map();
        for key in KNOWN_MODULE_KEYS {
            if let Some(value) = root_map.remove(*key) {
                modules.insert((*key).to_string(), value);
            }
        }

        let seen: HashSet<String> = layout
            .left
            .iter()
            .chain(layout.center.iter())
            .chain(layout.right.iter())
            .cloned()
            .collect();
        let mut hidden = Vec::new();
        for key in KNOWN_MODULE_KEYS {
            if !seen.contains(*key) {
                hidden.push((*key).to_string());
            }
        }

        WaybarConfigSnapshot {
            layout: WaybarLayout {
                left: dedupe(layout.left),
                center: dedupe(layout.center),
                right: dedupe(layout.right),
                hidden,
            },
            globals,
            modules,
            passthrough: Value::Object(root_map),
            raw_json,
        }
    }
}

fn dedupe(list: Vec<String>) -> Vec<String> {
    let mut seen = HashSet::new();
    list.into_iter()
        .filter(|item| seen.insert(item.clone()))
        .collect()
}

fn unique_ordered(list: Vec<String>, seen: &mut HashSet<String>) -> Vec<String> {
    let mut result = Vec::new();
    for item in list {
        if seen.insert(item.clone()) {
            result.push(item);
        }
    }
    result
}

fn number_from_f64(value: f64, fallback: f64) -> serde_json::Number {
    serde_json::Number::from_f64(value)
        .or_else(|| serde_json::Number::from_f64(fallback))
        .unwrap()
}

fn take_string_array(value: Option<Value>, fallback: Vec<String>) -> Vec<String> {
    match value {
        Some(Value::Array(items)) => items
            .into_iter()
            .filter_map(|entry| entry.as_str().map(|s| s.to_string()))
            .collect(),
        _ => fallback,
    }
}

fn default_left_modules() -> Vec<String> {
    vec![
        "custom/omarchy".to_string(),
        "hyprland/workspaces".to_string(),
    ]
}

fn default_center_modules() -> Vec<String> {
    vec![
        "clock".to_string(),
        "custom/update".to_string(),
        "custom/screenrecording-indicator".to_string(),
    ]
}

fn default_right_modules() -> Vec<String> {
    vec![
        "group/tray-expander".to_string(),
        "bluetooth".to_string(),
        "network".to_string(),
        "pulseaudio".to_string(),
        "cpu".to_string(),
        "battery".to_string(),
    ]
}

fn default_modules_map() -> BTreeMap<String, Value> {
    let mut map = BTreeMap::new();
    map.insert(
        "custom/omarchy".to_string(),
        json!({
            "format": "<span font='omarchy'>\u{e900}</span>",
            "on-click": "omarchy-menu",
            "tooltip-format": "Omarchy Menu\n\nSuper + Alt + Space"
        }),
    );
    map.insert(
        "clock".to_string(),
        json!({
            "format": "{:L%A %H:%M}",
            "format-alt": "{:L%d %B W%V %Y}",
            "tooltip": false,
            "on-click-right": "omarchy-cmd-tzupdate"
        }),
    );
    map.insert(
        "custom/update".to_string(),
        json!({
            "format": "",
            "exec": "omarchy-update-available",
            "on-click": "omarchy-launch-floating-terminal-with-presentation omarchy-update",
            "tooltip-format": "Omarchy update available",
            "signal": 7,
            "interval": 3600
        }),
    );
    map.insert(
        "custom/screenrecording-indicator".to_string(),
        json!({
            "on-click": "omarchy-cmd-screenrecord",
            "exec": "$OMARCHY_PATH/default/waybar/indicators/screen-recording.sh",
            "signal": 8,
            "return-type": "json"
        }),
    );
    map.insert(
        "hyprland/workspaces".to_string(),
        json!({
            "on-click": "activate",
            "format": "{icon}",
            "format-icons": {
                "default": "",
                "1": "1",
                "2": "2",
                "3": "3",
                "4": "4",
                "5": "5",
                "6": "6",
                "7": "7",
                "8": "8",
                "9": "9",
                "active": "󱓻"
            },
            "persistent-workspaces": {
                "1": [],
                "2": [],
                "3": [],
                "4": [],
                "5": []
            }
        }),
    );
    map.insert(
        "hyprland/window".to_string(),
        json!({
            "format": "{title}",
            "max-length": 50
        }),
    );
    map.insert(
        "group/tray-expander".to_string(),
        json!({
            "orientation": "inherit",
            "drawer": {
                "transition-duration": 600,
                "children-class": "tray-group-item"
            },
            "modules": ["custom/expand-icon", "tray"]
        }),
    );
    map.insert(
        "custom/expand-icon".to_string(),
        json!({
            "format": " ",
            "tooltip": false
        }),
    );
    map.insert(
        "tray".to_string(),
        json!({
            "icon-size": 12,
            "spacing": 12
        }),
    );
    map.insert(
        "bluetooth".to_string(),
        json!({
            "format": "",
            "format-disabled": "󰂲",
            "format-connected": "",
            "tooltip-format": "Devices connected: {num_connections}",
            "on-click": "blueberry"
        }),
    );
    map.insert(
        "network".to_string(),
        json!({
            "format-icons": ["󰤯", "󰤟", "󰤢", "󰤥", "󰤨"],
            "format": "{icon}",
            "format-wifi": "{icon}",
            "format-ethernet": "󰀂",
            "format-disconnected": "󰤮",
            "tooltip-format-wifi": "{essid} ({frequency} GHz)\n⇣{bandwidthDownBytes}  ⇡{bandwidthUpBytes}",
            "tooltip-format-ethernet": "⇣{bandwidthDownBytes}  ⇡{bandwidthUpBytes}",
            "tooltip-format-disconnected": "Disconnected",
            "interval": 3,
            "spacing": 1,
            "on-click": "omarchy-launch-wifi"
        }),
    );
    map.insert(
        "pulseaudio".to_string(),
        json!({
            "format": "{icon}",
            "on-click": "$TERMINAL --class=Wiremix -e wiremix",
            "on-click-right": "pamixer -t",
            "tooltip-format": "Playing at {volume}%",
            "scroll-step": 5,
            "format-muted": "",
            "format-icons": {
                "default": ["", "", ""]
            }
        }),
    );
    map.insert(
        "cpu".to_string(),
        json!({
            "interval": 5,
            "format": "󰍛",
            "on-click": "$TERMINAL -e btop"
        }),
    );
    map.insert(
        "battery".to_string(),
        json!({
            "format": "{capacity}% {icon}",
            "format-discharging": "{icon}",
            "format-charging": "{icon}",
            "format-plugged": "",
            "format-icons": {
                "charging": ["󰢜", "󰂆", "󰂇", "󰂈", "󰢝", "󰂉", "󰢞", "󰂊", "󰂋", "󰂅"],
                "default": ["󰁺", "󰁻", "󰁼", "󰁽", "󰁾", "󰁿", "󰂀", "󰂁", "󰂂", "󰁹"]
            },
            "format-full": "󰂅",
            "tooltip-format-discharging": "{power:>1.0f}W↓ {capacity}%",
            "tooltip-format-charging": "{power:>1.0f}W↑ {capacity}%",
            "interval": 5,
            "on-click": "omarchy-menu power",
            "states": {
                "warning": 20,
                "critical": 10
            }
        }),
    );
    map
}

fn default_root_value() -> Value {
    let mut map = Map::new();
    let global_defaults = WaybarGlobals::default();
    map.insert("reload_style_on_change".to_string(), Value::Bool(true));
    map.insert("layer".to_string(), Value::String("top".to_string()));
    map.insert("position".to_string(), Value::String("top".to_string()));
    map.insert(
        "height".to_string(),
        Value::Number(number_from_f64(global_defaults.height, 26.0)),
    );
    map.insert(
        "spacing".to_string(),
        Value::Number(number_from_f64(global_defaults.spacing, 0.0)),
    );
    map.insert(
        "modules-left".to_string(),
        Value::Array(
            default_left_modules()
                .into_iter()
                .map(Value::String)
                .collect(),
        ),
    );
    map.insert(
        "modules-center".to_string(),
        Value::Array(
            default_center_modules()
                .into_iter()
                .map(Value::String)
                .collect(),
        ),
    );
    map.insert(
        "modules-right".to_string(),
        Value::Array(
            default_right_modules()
                .into_iter()
                .map(Value::String)
                .collect(),
        ),
    );

    let defaults = default_modules_map();
    for key in [
        "custom/omarchy",
        "hyprland/workspaces",
        "clock",
        "custom/update",
        "custom/screenrecording-indicator",
        "group/tray-expander",
        "custom/expand-icon",
        "tray",
        "bluetooth",
        "network",
        "pulseaudio",
        "cpu",
        "battery",
    ] {
        if let Some(value) = defaults.get(key).cloned() {
            map.insert(key.to_string(), value);
        }
    }

    Value::Object(map)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn default_config_contains_known_modules() {
        let value = default_root_value();
        let snapshot = WaybarConfigService {
            config_path: PathBuf::from("/tmp/waybar.jsonc"),
        }
        .build_snapshot(value.clone(), serde_json::to_string_pretty(&value).unwrap());
        assert_eq!(snapshot.layout.left.len(), 2);
        assert_eq!(snapshot.layout.center.len(), 3);
        assert_eq!(snapshot.layout.right.len(), 6);
        assert!(snapshot.modules.contains_key("custom/omarchy"));
    }
}
