use crate::error::Result;
use std::path::Path;

use crate::system::omarchy_paths::user_themes_dir;
use crate::system::themes::color_extractor::{
    ColorPalette, copy_image_to_backgrounds, extract_palette,
};
use crate::system::themes::color_utils::adjust_brightness;
use crate::system::themes::icons;
use crate::system::themes::theme_management::{create_theme_from_defaults, save_theme_data};
use crate::types::themes::{ColorsConfig, EditingTheme};

// Create a complete theme from an image. A failure after the folder was
// created removes it again, so a half-made theme never lingers on the
// Themes page.
pub fn create_theme_from_image(image_path: &Path, theme_name: &str) -> Result<String> {
    let palette = extract_palette(image_path)?;

    create_theme_from_defaults(theme_name)?;

    let filled = (|| {
        let editing_theme = build_theme_from_palette(&palette, theme_name);
        save_theme_data(theme_name, &editing_theme)?;

        icons::write(theme_name, icons::closest_to(&palette.accent))?;

        copy_image_to_backgrounds(image_path, theme_name)
    })();
    if let Err(e) = filled {
        if let Some(dir) = user_themes_dir() {
            let _ = std::fs::remove_dir_all(dir.join(theme_name));
        }
        return Err(e);
    }

    Ok(theme_name.to_string())
}

// Build a complete EditingTheme from a color palette
fn build_theme_from_palette(palette: &ColorPalette, theme_name: &str) -> EditingTheme {
    use chrono::Utc;

    let now = Utc::now().to_rfc3339();

    // colors.toml is the sole source of truth for the theme's palette — every
    // other app (terminal, bar, notifications, window borders) is
    // template-generated by Omarchy itself from these values.
    let colors_config = ColorsConfig {
        mode: if palette.is_light_theme {
            "light"
        } else {
            "dark"
        }
        .to_string(),
        accent: palette.accent.clone(),
        foreground: palette.foreground.clone(),
        background: palette.background.clone(),
        selection_foreground: palette.foreground.clone(),
        selection_background: adjust_brightness(
            &palette.accent,
            if palette.is_light_theme { 0.25 } else { -0.25 },
        ),
        color0: palette.terminal.black.clone(),
        color1: palette.terminal.red.clone(),
        color2: palette.terminal.green.clone(),
        color3: palette.terminal.yellow.clone(),
        color4: palette.terminal.blue.clone(),
        color5: palette.terminal.magenta.clone(),
        color6: palette.terminal.cyan.clone(),
        color7: palette.terminal.white.clone(),
        color8: palette.bright.black.clone(),
        color9: palette.bright.red.clone(),
        color10: palette.bright.green.clone(),
        color11: palette.bright.yellow.clone(),
        color12: palette.bright.blue.clone(),
        color13: palette.bright.magenta.clone(),
        color14: palette.bright.cyan.clone(),
        color15: palette.bright.white.clone(),
        hyprland_active_border: None,
        hyprland_inactive_border: None,
        extra: Vec::new(),
    };

    EditingTheme {
        version: "2.0.0".to_string(),
        name: theme_name.to_string(),
        created_at: now.clone(),
        modified_at: now,
        author: None,
        colors: colors_config,
        is_light_theme: palette.is_light_theme,
    }
}
